apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-time-api
  namespace: app-time
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: pkasianov/app-time-api:latest
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-pass
            - name: MYSQL_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-name
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: app-time
spec:
  ports:
    - port: 5555
      targetPort: 5000
  selector:
    app: api