apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-time-mysql
  namespace: app-time
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-pass
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-name
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: [ "mysqladmin", "ping", "-h", "localhost" ]
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-database
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: app-time
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql